version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      STAGE: dev                     
      DB_HOST: db                    
      DB_PORT: 5432
      DB_USERNAME: joshdebele
      DB_PASSWORD: Yolo123$
      DB_DATABASE: scription
      JWT_SECRET: 0f6904993819c474ce7b6c58ea844950b4c05382516e86d5870c68de5957538f91b331d092533c1f63019217329df903a942696b3dc6327584adb412b2cd0ddb
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: joshdebele
      POSTGRES_PASSWORD: Yolo123$
      POSTGRES_DB: scription
      DB_HOST: db
